In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [1,1],
    [2,2],
    [3,1],
    [8,8],
    [9,9],
    [8,9]

])

In [ ]:
names = ['A','B','C','D','E','F']

In [ ]:
K = 2

In [ ]:
centroids = np.array([
    [1,1],
    [8,8]
], dtype=float)

In [ ]:
print("Intial Centroids")
print(centroids)

Intial Centroids
[[1. 1.]
 [8. 8.]]


In [ ]:
for iteration in range(10):

  print("\nIteration ", iteration +1)

  distances = np.sqrt(
      ((X[:, np.newaxis, :] - centroids[np.newaxis,:,:]) ** 2).sum(axis=2)
  )

  print("\n Distances:")
  print(distances)

  clusters = np.argmin(distances, axis=1)

  print("\nCluster Assignment:")
  for i in range(len(X)):
    print(names[i],"-> Cluster", clusters[i] +1)

  new_centroids = np.array([
      X[clusters == k].mean(axis=0)
      for k in range(K)
  ])

  print("\nNew Centroids:")
  print(new_centroids)

  if np.allclose(centroids, new_centroids):
    print("\nCentroids have stopped changing.")
    break

  centroids = new_centroids


Iteration  1

 Distances:
[[ 0.          9.89949494]
 [ 1.41421356  8.48528137]
 [ 2.          8.60232527]
 [ 9.89949494  0.        ]
 [11.3137085   1.41421356]
 [10.63014581  1.        ]]

Cluster Assignment:
A -> Cluster 1
B -> Cluster 1
C -> Cluster 1
D -> Cluster 2
E -> Cluster 2
F -> Cluster 2

New Centroids:
[[2.         1.33333333]
 [8.33333333 8.66666667]]

Iteration  2

 Distances:
[[ 1.05409255 10.60922031]
 [ 0.66666667  9.19540948]
 [ 1.05409255  9.33928382]
 [ 8.9690827   0.74535599]
 [10.38160767  0.74535599]
 [ 9.73538791  0.47140452]]

Cluster Assignment:
A -> Cluster 1
B -> Cluster 1
C -> Cluster 1
D -> Cluster 2
E -> Cluster 2
F -> Cluster 2

New Centroids:
[[2.         1.33333333]
 [8.33333333 8.66666667]]

Centroids have stopped changing.


In [ ]:
print("\nFinal Centroids: ")
print(centroids)

print("\nFinal Clusters:")

for k in range(K):
  print("\nCluster", k+1)

  for i in range(len(X)):
    if clusters[i] == k:
      print(names[i], "->", X[i])


Final Centroids: 
[[2.         1.33333333]
 [8.33333333 8.66666667]]

Final Clusters:

Cluster 1
A -> [1 1]
B -> [2 2]
C -> [3 1]

Cluster 2
D -> [8 8]
E -> [9 9]
F -> [8 9]
