In [ ]:
import numpy as np

In [ ]:
X = np.array(
    [1,2,3,4,5,]
)

In [ ]:
y = np.array([35,45,60,82,110])

In [ ]:
X_poly = np.column_stack((np.ones(len(X)),X, X**2))

In [ ]:
print("Polynomial Features")
print(X_poly)

Polynomial Features
[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


In [ ]:
beta = np.linalg.inv(X_poly.T @ X_poly) @ X_poly.T @ y

print("Intercept:", beta[0])
print("Coefficient of X:", beta[1])
print("Coefficient of X²:", beta[2])

Intercept: 31.799999999999805
Coefficient of X: 0.27142857142887955
Coefficient of X²: 3.07142857142853


In [ ]:
x_new = np.array([1, 6, 36])   # [1, X, X²]
prediction = x_new @ beta

print("Predicted Value:", prediction)

Predicted Value: 144.00000000000017
